apiVersion: apps/v1
kind: Deployment
metadata:
  name: example01
spec:
  replicas: 4
  selector:
    matchLabels:
      app-name: app01
  template:
    metadata:
      labels:
        app-name: app01
    spec:
      containers:
      - image: busybox
        name: container1
        command: ["sleep", "infinity"]
