apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app01
  template:
    metadata:
      labels:
        app: example-app01
    spec:
      containers:
      - image: busybox
        name: example-app01
        command: ["sleep", "3600"]
