apiVersion: apps/v1
kind: Deployment
metadata:
  name: example01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example01
  template:
    metadata:
      labels:
        app: example01
    spec:
      containers:
      - image: busybox
        name: container1
        command: ["sleep", "3600"]
