---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-configmap
data:
  index.html: |-
    <html>
    <head>
    <title>...Wellcome in ArgoCD...</title>
    </head>
    <body>
    Hello this is ArgoCD Daemon Set!</br>
    <b>This is update hope will be visible in Argo :)</b>
    </body>
    </html>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example02
  labels:
    app-name: app02
spec:
  selector:
    matchLabels:
      app-name: app02
  template:
    metadata:
      labels:
        app-name: app02
    spec:
      containers:
      - name: webserver
        image: nginx:latest
        volumeMounts:
        - name: index-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index-volume
        configMap:
          name: nginx-index-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: example-app02-svc
spec:
  selector:
    app-name: app02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
