---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-file-config-map
data:
  index.html: |-
    <html>
    <body>
    Hell my name is Janusz
    </body>
    </html>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-app02
  labels:
    app-name: app02
spec:
  selector:
    matchLabels:
      app-name: app02
  template:
    metadata:
      labels:
        app-name: app02
    spec:
      containers:
      - name: webserver
        image: nginx:latest
        volumeMounts:
        - name: index.html
          mountPath: /usr/share/nginx/html
      volumes:
      - configMap:
          name: nginx-index-file-config-map
        name: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: example-app02-svc
spec:
  selector:
    app-name: app02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
