apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-file-config-map
data:
  index-file: |-
    <html>
    <body>
    Hell my name is Janusz
    </body>
    </html>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-app02
  labels:
    app: example-app02  
spec:
  selector:
    matchLabels:
      app: example-app02
    template:
      metadata:
        labels:
          name: example-app02
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          volumeMounts:
          - name: index-file        
            mountPath: /usr/share/nginx/www/index.html              
        volumes:                
        - configMap: 
            name: nginx-index-file-config-map
          name: index-file
---
apiVersion: v1
kind: Service
metadata:
  name: example-app02-svc
spec:
  selector:
    app: example-app02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
type: NodePort
  
